<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Exercise::insert([
            [
                'id' => 1,
                'name' => 'Sentadilla libre',
                'description' => 'Flexiona las rodillas de acuerdo a tu biomecánica',
                'muscle_group' => 'cuadriceps',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:28:35',
                'updated_at' => '2023-10-21 06:28:35',
            ],
            [
                'id' => 2,
                'name' => 'Press de banca',
                'description' => 'Levantamiento de pesas sobre un banco',
                'muscle_group' => 'pectorales',
                'equipment' => 'banco',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:29:28',
                'updated_at' => '2023-10-21 06:29:28',
            ],
            [
                'id' => 3,
                'name' => 'Dominadas',
                'description' => 'Suspenderse de una barra y levantar el cuerpo',
                'muscle_group' => 'espalda',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:29:49',
                'updated_at' => '2023-10-21 06:29:49',
            ],
            [
                'id' => 4,
                'name' => 'Curl de Bíceps',
                'description' => 'Flexión de codos con pesas para trabajar los bíceps',
                'muscle_group' => 'biceps',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:30:12',
                'updated_at' => '2023-10-21 06:30:12',
            ],
            [
                'id' => 5,
                'name' => 'Prensa de Piernas',
                'description' => 'Levantamiento de pesas con las piernas',
                'muscle_group' => 'cuadriceps',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:30:42',
                'updated_at' => '2023-10-21 06:30:42',
            ],
            [
                'id' => 6,
                'name' => 'Peso Muerto',
                'description' => 'Levantamiento con barra desde el suelo',
                'muscle_group' => 'gluteos',
                'equipment' => 'barra',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:31:39',
                'updated_at' => '2023-10-21 06:31:39',
            ],
            [
                'id' => 7,
                'name' => 'Copa de tríceps',
                'description' => 'Flexión de codos con las manos juntas detrás de ti',
                'muscle_group' => 'triceps',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:34:49',
                'updated_at' => '2023-10-21 06:34:49',
            ],
            [
                'id' => 8,
                'name' => 'Abdominales Crunch',
                'description' => 'Flexión de torso para trabajar los abdominales',
                'muscle_group' => 'abdomen',
                'equipment' => 'ninguno',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:36:53',
                'updated_at' => '2023-10-21 06:36:53',
            ],
            [
                'id' => 9,
                'name' => 'Press Militar',
                'description' => 'Levantamiento de pesas sobre la cabeza',
                'muscle_group' => 'hombros',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:38:20',
                'updated_at' => '2023-10-21 06:38:20',
            ],
            [
                'id' => 10,
                'name' => 'Pájaros',
                'description' => 'Elevación lateral de pesas para deltoides',
                'muscle_group' => 'hombros',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:38:38',
                'updated_at' => '2023-10-21 06:38:38',
            ],
            [
                'id' => 11,
                'name' => 'Hip Thrust',
                'description' => 'Elevación de cadera con peso para glúteos',
                'muscle_group' => 'gluteos',
                'equipment' => 'barra',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:39:07',
                'updated_at' => '2023-10-21 06:39:07',
            ],
            [
                'id' => 12,
                'name' => 'Curl de Bíceps con Barra',
                'description' => 'Flexión de codos con barra',
                'muscle_group' => 'biceps',
                'equipment' => 'barra',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:41:54',
                'updated_at' => '2023-10-21 06:41:54',
            ],
            [
                'id' => 13,
                'name' => 'Curl de Martillo',
                'description' => 'Curl con mancuernas en posición neutral',
                'muscle_group' => 'biceps',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:42:10',
                'updated_at' => '2023-10-21 06:42:10',
            ],
            [
                'id' => 14,
                'name' => 'Curl de Concentración',
                'description' => 'Curl de bíceps aislado',
                'muscle_group' => 'biceps',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:42:24',
                'updated_at' => '2023-10-21 06:42:24',
            ],
            [
                'id' => 15,
                'name' => 'Curl 21s',
                'description' => 'Combinación de curl de bíceps con barra o mancuernas',
                'muscle_group' => 'biceps',
                'equipment' => 'barra',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:42:55',
                'updated_at' => '2023-10-21 06:42:55',
            ],
            [
                'id' => 16,
                'name' => 'Extensiones de Tríceps en Polea Alta',
                'description' => 'Extensión de codos en polea alta',
                'muscle_group' => 'triceps',
                'equipment' => 'polea',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:48:05',
                'updated_at' => '2023-10-21 06:48:05',
            ],
            [
                'id' => 17,
                'name' => 'Fondos en Máquina',
                'description' => 'Extensión de codos en máquina',
                'muscle_group' => 'triceps',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:48:21',
                'updated_at' => '2023-10-21 06:48:21',
            ],
            [
                'id' => 18,
                'name' => 'Patada de tríceps',
                'description' => 'Extensión de codo con espalda recta',
                'muscle_group' => 'triceps',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:49:20',
                'updated_at' => '2023-10-21 06:49:20',
            ],
            [
                'id' => 19,
                'name' => 'Fondos en Paralelas',
                'description' => 'Suspenderse y levantar el cuerpo',
                'muscle_group' => 'pectorales',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:49:47',
                'updated_at' => '2023-10-21 06:49:47',
            ],
            [
                'id' => 20,
                'name' => 'Press Inclinado con Mancuernas',
                'description' => 'Levantamiento de pesas en posición inclinada',
                'muscle_group' => 'pectorales',
                'equipment' => 'banco',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:50:05',
                'updated_at' => '2023-10-21 06:50:05',
            ],
            [
                'id' => 21,
                'name' => 'Pullover con Barra',
                'description' => 'Extensión de brazos con barra sobre el pecho',
                'muscle_group' => 'pectorales',
                'equipment' => 'banco',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:51:05',
                'updated_at' => '2023-10-21 06:51:05',
            ],
            [
                'id' => 22,
                'name' => 'Aperturas en Máquina de Pecho',
                'description' => 'Movimiento de apertura en máquina',
                'muscle_group' => 'pectorales',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:51:21',
                'updated_at' => '2023-10-21 06:51:21',
            ],
            [
                'id' => 23,
                'name' => 'Remo con Barra T',
                'description' => 'Levantamiento de barra en posición tumbada',
                'muscle_group' => 'espalda',
                'equipment' => 'barra',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:52:37',
                'updated_at' => '2023-10-21 06:52:37',
            ],
            [
                'id' => 24,
                'name' => 'Pulldown en Polea Alta',
                'description' => 'Tracción en polea alta',
                'muscle_group' => 'espalda',
                'equipment' => 'polea',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:52:58',
                'updated_at' => '2023-10-21 06:52:58',
            ],
            [
                'id' => 25,
                'name' => 'Extensiones de Piernas',
                'description' => 'Extensión de piernas en máquina',
                'muscle_group' => 'cuadriceps',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:56:25',
                'updated_at' => '2023-10-21 06:56:25',
            ],
            [
                'id' => 26,
                'name' => 'Zancadas',
                'description' => 'Pasos largos alternos hacia adelante o hacia atrás',
                'muscle_group' => 'cuadriceps',
                'equipment' => 'ninguno',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:57:02',
                'updated_at' => '2023-10-21 06:57:02',
            ],
            [
                'id' => 27,
                'name' => 'Sentadillas Búlgaras',
                'description' => 'Variantes de sentadillas',
                'muscle_group' => 'femorales',
                'equipment' => 'mancuernas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:57:50',
                'updated_at' => '2023-10-21 06:57:50',
            ],
            [
                'id' => 28,
                'name' => 'Elevación de Talones',
                'description' => 'Elevación de talones de pie en escaleras',
                'muscle_group' => 'pantorrilla',
                'equipment' => 'ninguno',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:58:34',
                'updated_at' => '2023-10-21 06:58:34',
            ],
            [
                'id' => 29,
                'name' => 'Prensa de Pantorrilla',
                'description' => 'Extensión de pantorilla en prensa',
                'muscle_group' => 'pantorrilla',
                'equipment' => 'máquina especial',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 06:59:30',
                'updated_at' => '2023-10-21 06:59:30',
            ],
            [
                'id' => 30,
                'name' => 'Plancha',
                'description' => 'Mantenimiento del cuerpo en forma de plancha',
                'muscle_group' => 'abdomen',
                'equipment' => 'ninguno',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 07:00:11',
                'updated_at' => '2023-10-21 07:00:11',
            ],
            [
                'id' => 31,
                'name' => 'Sentadillas Sumo',
                'description' => 'Bajar con piernas abiertas como peso muerto romano',
                'muscle_group' => 'gluteos',
                'equipment' => 'pesas rusas',
                'media' => "https://res.cloudinary.com/des5tlbfo/image/upload/v1701326986/gym/exercises/u9lbjcebdgdbzg8ofyrh.jpg",
                'created_at' => '2023-10-21 07:02:46',
                'updated_at' => '2023-10-21 07:02:46',
            ],
        ]);
    }
}
