<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Food::insert([
            [
                'id' => 1,
                'name' => 'Avena en hojuelas',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/3 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 2,
                'name' => 'Arroz blanco o integral cocido',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 3,
                'name' => 'Elote cocido',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 4,
                'name' => 'Cereal de caja con azúcar',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/3 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 5,
                'name' => 'Galleta María',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '5 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 6,
                'name' => 'Hot cake (1 pieza chica)',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 7,
                'name' => 'Palomitas naturales',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '3 tazas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 8,
                'name' => 'Pan birote',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 9,
                'name' => 'Pan de caja (blanco, integral, multigrano)',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 10,
                'name' => 'Pan tostado',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 11,
                'name' => 'Pasta hervida (fideo, espagueti, lasaña, etc.)',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 12,
                'name' => 'Tortilla de maíz',
                'group' => 'Cereales y tubérculos sin grasa',
                'info' => '{"Grasa": "0g", "Energia": "70 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 13,
                'name' => 'Barra de granola',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 14,
                'name' => 'Palomitas con mantequilla',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 15,
                'name' => 'Papas fritas',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '6 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 16,
                'name' => 'Totopos y nachos',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '4 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 17,
                'name' => 'Tamal',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1/4 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 18,
                'name' => 'Tostada',
                'group' => 'Cereales y tubérculos con grasa',
                'info' => '{"Grasa": "5g", "Energia": "115 kcal", "Proteinas": "2g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 19,
                'name' => 'Brócoli cocido',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 20,
                'name' => 'Chayote cocido',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 21,
                'name' => 'Chícharo',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '3 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 22,
                'name' => 'Jicama picada',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 23,
                'name' => 'Jugo de zanahoria',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1/4 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 24,
                'name' => 'Zanahoria Picada o rallada',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 25,
                'name' => 'Pepino rebanado',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1 1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 26,
                'name' => 'Lechuga',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '3 tazas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 27,
                'name' => 'Coliflor cocida',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 28,
                'name' => 'Champiñón',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 29,
                'name' => 'Alcachofa',
                'group' => 'Verduras',
                'info' => '{"Grasa": "0g", "Energia": "25 kcal", "Proteinas": "2g", "Carbohidratos": "4g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 30,
                'name' => 'Agua de coco',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 31,
                'name' => 'Arándano',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 32,
                'name' => 'Durazno (chico)',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '2 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 33,
                'name' => 'Fresa rebanada',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 34,
                'name' => 'Guayaba',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '3 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 35,
                'name' => 'Kiwi',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 36,
                'name' => 'Lima',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '3 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 37,
                'name' => 'Limón real',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '4 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 38,
                'name' => 'Manzana (chica)',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 39,
                'name' => 'Naranja',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 40,
                'name' => 'Pera',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1/2 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 41,
                'name' => 'Piña picada',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '3/4 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 42,
                'name' => 'Sandía picada',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 43,
                'name' => 'Toronja',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 44,
                'name' => 'Uva roja o verde',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '15 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 45,
                'name' => 'Pasas',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '10 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 46,
                'name' => 'Plátano macho',
                'group' => 'Frutas',
                'info' => '{"Grasa": "0g", "Energia": "60 kcal", "Proteinas": "0g", "Carbohidratos": "15g"}',
                'portion' => '1/4 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 47,
                'name' => 'Atún en agua',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '40 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 48,
                'name' => 'Bistec de res',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 49,
                'name' => 'Calamar',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '50 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 50,
                'name' => 'Camarón cocido',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '5 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 51,
                'name' => 'Clara de huevo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '2 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 52,
                'name' => 'Filete de pescado',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '40 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 53,
                'name' => 'Filete de res',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 54,
                'name' => 'Pechuga a la plancha',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 55,
                'name' => 'Pechuga de pavo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '2 rebanadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 56,
                'name' => '2 rebanadas',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "1g", "Energia": "40 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 57,
                'name' => 'Arrachera',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos / 2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 58,
                'name' => 'Atún en aceite',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos / 2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 59,
                'name' => 'Conejo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '45 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 60,
                'name' => 'Filete de salmón',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos / 2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 61,
                'name' => 'Filete de cerdo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '40 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 62,
                'name' => 'Jamón de pavo y/o pierna',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '2 rebanadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 63,
                'name' => 'Salmón',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos / 2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 64,
                'name' => 'Bistec de bola',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '25 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 65,
                'name' => 'Carne de suadero',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '29 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 66,
                'name' => 'Chicharrón',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '12 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 67,
                'name' => 'Huevo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 68,
                'name' => 'Queso mozarella',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '30 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 69,
                'name' => 'Salchicha de cerdo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '3/4 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 70,
                'name' => 'Nuggets de pollo',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '2 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 71,
                'name' => 'Pollo rostizado',
                'group' => 'Alimentos de origen animal',
                'info' => '{"Grasa": "3g", "Energia": "55 kcal", "Proteinas": "7g", "Carbohidratos": "0g"}',
                'portion' => '50 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 72,
                'name' => 'Leche de soya baja en grasa',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "2g", "Energia": "95 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 73,
                'name' => 'Leche descremada',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "2g", "Energia": "95 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 74,
                'name' => 'Leche en polvo descremada',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "2g", "Energia": "95 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '4 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 75,
                'name' => 'Yogurt light',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "2g", "Energia": "95 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '3/4 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 76,
                'name' => 'Yogurt para beber bajo en grasa y azúcar',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "2g", "Energia": "95 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 77,
                'name' => 'Leche en polvo',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "8g", "Energia": "150 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '4 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 78,
                'name' => 'Leche entera',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "8g", "Energia": "150 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 79,
                'name' => 'Leche liconsa',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "8g", "Energia": "150 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1/4 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 80,
                'name' => 'Yogurt natura',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "8g", "Energia": "150 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 81,
                'name' => 'Yogurt para beber con fruta',
                'group' => 'Alimentos con contenido moderado y alto de calcio',
                'info' => '{"Grasa": "8g", "Energia": "150 kcal", "Proteinas": "9g", "Carbohidratos": "12g"}',
                'portion' => '1 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 82,
                'name' => 'Alubias, garbanzos, habas, lentejas cocidas',
                'group' => 'Leguminosas',
                'info' => '{"Grasa": "1g", "Energia": "120 kcal", "Proteinas": "8g", "Carbohidratos": "20g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 83,
                'name' => 'Frijol canario, negro cocido',
                'group' => 'Leguminosas',
                'info' => '{"Grasa": "1g", "Energia": "120 kcal", "Proteinas": "8g", "Carbohidratos": "20g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 84,
                'name' => 'Soya cocida',
                'group' => 'Leguminosas',
                'info' => '{"Grasa": "1g", "Energia": "120 kcal", "Proteinas": "8g", "Carbohidratos": "20g"}',
                'portion' => '1/3 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 85,
                'name' => 'Soya texturizada seca',
                'group' => 'Leguminosas',
                'info' => '{"Grasa": "1g", "Energia": "120 kcal", "Proteinas": "8g", "Carbohidratos": "20g"}',
                'portion' => '35 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 86,
                'name' => 'Alverjón',
                'group' => 'Leguminosas',
                'info' => '{"Grasa": "1g", "Energia": "120 kcal", "Proteinas": "8g", "Carbohidratos": "20g"}',
                'portion' => '1/2 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 87,
                'name' => 'Aguacate',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '1/3 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 88,
                'name' => 'Almendras',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '10 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 89,
                'name' => 'Cacahuates',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '14 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 90,
                'name' => 'Pistaches',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '18 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 91,
                'name' => 'Nuez de la india',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '7 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 92,
                'name' => 'Nuez',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '3 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 93,
                'name' => 'Mayonesa',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '1 cucharadita',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 94,
                'name' => 'Guacamole',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 95,
                'name' => 'Cacahuates con cáscara',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '12 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 96,
                'name' => 'Aceituna verde',
                'group' => 'Grasas con proteína',
                'info' => '{"Grasa": "5g", "Energia": "70 kcal", "Proteinas": "3g", "Carbohidratos": "3g"}',
                'portion' => '6 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 97,
                'name' => 'Aceite de canola, soya, oliva',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharadita',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 98,
                'name' => 'Aceite de girasol, maíz, cártamo',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharadita',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 99,
                'name' => 'Aceite en spray',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '5 disparos de 1 segundo',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 100,
                'name' => 'Pepitas sin cáscara',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 101,
                'name' => 'Piñón',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharadita',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 102,
                'name' => 'Chorizo',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 103,
                'name' => 'Coco',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '8 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 104,
                'name' => 'Crema',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 105,
                'name' => 'Crema chantilly',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 1/2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 106,
                'name' => 'Crema para café',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 107,
                'name' => 'Mantequilla',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 1/2 cucharaditas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 108,
                'name' => 'Pepperoni',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '4 rebanadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 109,
                'name' => 'Queso crema',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 110,
                'name' => 'Mole poblano en pasta',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 cucharadita',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 111,
                'name' => 'Tocino en tira',
                'group' => 'Grasas',
                'info' => '{"Grasa": "5g", "Energia": "45 kcal", "Proteinas": "0g", "Carbohidratos": "0g"}',
                'portion' => '1 rebanada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 112,
                'name' => 'Cajeta',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1 1/2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 113,
                'name' => 'Chicle',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '5 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 114,
                'name' => 'Gelatina preparada con agua',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/3 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 115,
                'name' => 'Gomitas',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '4 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 116,
                'name' => 'Malvavisco',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '2 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 117,
                'name' => 'Miel (de abeja, maíz o maple)',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '2 cucharaditas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 118,
                'name' => 'Obleas de cajeta',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 119,
                'name' => 'Piloncillo',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '10 gramos',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 120,
                'name' => 'Salsa catsup',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '2 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 121,
                'name' => 'Refrescos embotellados',
                'group' => 'Azúcares',
                'info' => '{"Grasa": "0g", "Energia": "40 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/4 de lata',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 122,
                'name' => 'Almendra con chocolate',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1 cucharada',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 123,
                'name' => 'Chocolate amargo',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/3 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 124,
                'name' => 'Chocolate sin azúcar',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '3 cucharaditas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 125,
                'name' => 'Flan de caja',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/5 taza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 126,
                'name' => 'Lunetas',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/3 de paquete',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 127,
                'name' => 'Mole',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '3 cucharadas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [

                'id' => 128,
                'name' => 'Palanqueta',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/3 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 129,
                'name' => 'Paleta helada con leche o crema',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/5 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 130,
                'name' => 'Pasitas con chocolate',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '11 piezas',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
            [
                'id' => 131,
                'name' => 'Palanqueta de Cacahuate',
                'group' => 'Azúcares con grasa',
                'info' => '{"Grasa": "5g", "Energia": "85 kcal", "Proteinas": "0g", "Carbohidratos": "10g"}',
                'portion' => '1/3 pieza',
                'created_at' => '2023-10-29 20:33:32',
                'updated_at' => '2023-10-29 20:33:32',
            ],
        ]);
    }
}
